/**
 * SMMN Anchor Program Loaders
 *
 * Loaders and instruction builders for on-chain Anchor programs:
 * - backerRound: slot management and artist fee release
 * - staking: $SUMMON token staking
 * - revenueShare: profit distribution waterfall
 *
 * @module v3/plugins/smmn/infrastructure/anchor-programs
 */

import { Connection, PublicKey, type Signer } from '@solana/web3.js';
import { Program, AnchorProvider, Wallet, BN, type Idl } from '@coral-xyz/anchor';
import type { SMMNConfig } from '../domain/types.js';

// =============================================================================
// Minimal Stub IDLs
// =============================================================================
// Full IDLs would be loaded from JSON files generated by `anchor build`.
// These stubs enable TypeScript compilation and testing without deployed programs.

const BACKER_ROUND_IDL: Idl = {
  version: '0.1.0',
  name: 'backer_round',
  instructions: [
    {
      name: 'initialize',
      accounts: [
        { name: 'backerRound', isMut: true, isSigner: false },
        { name: 'authority', isMut: true, isSigner: true },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'totalSlots', type: 'u16' },
        { name: 'slotPrice', type: 'u64' },
        { name: 'platformFeeBps', type: 'u16' },
        { name: 'deadline', type: 'i64' },
      ],
    },
    {
      name: 'purchaseSlot',
      accounts: [
        { name: 'backerRound', isMut: true, isSigner: false },
        { name: 'backer', isMut: true, isSigner: true },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [],
    },
    {
      name: 'finalize',
      accounts: [
        { name: 'backerRound', isMut: true, isSigner: false },
        { name: 'artistWallet', isMut: true, isSigner: false },
        { name: 'authority', isMut: false, isSigner: true },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ],
      args: [],
    },
    {
      name: 'cancel',
      accounts: [
        { name: 'backerRound', isMut: true, isSigner: false },
        { name: 'authority', isMut: false, isSigner: true },
      ],
      args: [],
    },
  ],
  accounts: [
    {
      name: 'BackerRoundState',
      type: {
        kind: 'struct' as const,
        fields: [
          { name: 'totalSlots', type: 'u16' },
          { name: 'filledSlots', type: 'u16' },
          { name: 'slotPrice', type: 'u64' },
          { name: 'platformFeeBps', type: 'u16' },
          { name: 'deadline', type: 'i64' },
          { name: 'status', type: 'u8' },
        ],
      },
    },
  ],
  errors: [
    { code: 6000, name: 'RoundFull', msg: 'All backer slots are filled' },
    { code: 6001, name: 'RoundClosed', msg: 'Backer round is not open' },
    { code: 6002, name: 'DeadlinePassed', msg: 'Backer round deadline has passed' },
  ],
};

const STAKING_IDL: Idl = {
  version: '0.1.0',
  name: 'summon_staking',
  instructions: [
    {
      name: 'stake',
      accounts: [
        { name: 'stakingPool', isMut: true, isSigner: false },
        { name: 'userStake', isMut: true, isSigner: false },
        { name: 'userTokenAccount', isMut: true, isSigner: false },
        { name: 'poolVault', isMut: true, isSigner: false },
        { name: 'user', isMut: false, isSigner: true },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [{ name: 'amount', type: 'u64' }],
    },
    {
      name: 'unstake',
      accounts: [
        { name: 'stakingPool', isMut: true, isSigner: false },
        { name: 'userStake', isMut: true, isSigner: false },
        { name: 'userTokenAccount', isMut: true, isSigner: false },
        { name: 'poolVault', isMut: true, isSigner: false },
        { name: 'user', isMut: false, isSigner: true },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [{ name: 'amount', type: 'u64' }],
    },
    {
      name: 'claimYield',
      accounts: [
        { name: 'stakingPool', isMut: true, isSigner: false },
        { name: 'userStake', isMut: true, isSigner: false },
        { name: 'userTokenAccount', isMut: true, isSigner: false },
        { name: 'poolVault', isMut: true, isSigner: false },
        { name: 'user', isMut: false, isSigner: true },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [],
    },
  ],
  accounts: [
    {
      name: 'UserStake',
      type: {
        kind: 'struct' as const,
        fields: [
          { name: 'owner', type: 'publicKey' },
          { name: 'amountStaked', type: 'u64' },
          { name: 'pendingYield', type: 'u64' },
          { name: 'stakedAt', type: 'i64' },
        ],
      },
    },
  ],
  errors: [
    { code: 6000, name: 'InsufficientBalance', msg: 'Insufficient token balance' },
    { code: 6001, name: 'NothingStaked', msg: 'No tokens staked' },
  ],
};

const REVENUE_SHARE_IDL: Idl = {
  version: '0.1.0',
  name: 'revenue_share',
  instructions: [
    {
      name: 'distribute',
      accounts: [
        { name: 'revenuePool', isMut: true, isSigner: false },
        { name: 'buybackVault', isMut: true, isSigner: false },
        { name: 'stakingVault', isMut: true, isSigner: false },
        { name: 'smmnVault', isMut: true, isSigner: false },
        { name: 'authority', isMut: false, isSigner: true },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'buybackBps', type: 'u16' },
        { name: 'stakingBps', type: 'u16' },
        { name: 'smmnBps', type: 'u16' },
      ],
    },
  ],
  accounts: [],
  errors: [],
};

// =============================================================================
// Anchor Program Wrappers
// =============================================================================

export class AnchorProgramError extends Error {
  constructor(program: string, cause: unknown) {
    super(`Anchor program error [${program}]: ${String(cause)}`);
    this.name = 'AnchorProgramError';
  }
}

/** Creates a read-only AnchorProvider (no wallet required for reads) */
function createReadProvider(connection: Connection): AnchorProvider {
  // Minimal wallet stub for read-only operations
  const wallet = {
    publicKey: PublicKey.default,
    signTransaction: async <T>(tx: T) => tx,
    signAllTransactions: async <T>(txs: T[]) => txs,
  };
  return new AnchorProvider(connection, wallet as unknown as Wallet, {
    commitment: 'confirmed',
    preflightCommitment: 'confirmed',
  });
}

/**
 * Load the backerRound Anchor program.
 */
export function loadBackerRoundProgram(
  connection: Connection,
  wallet: Wallet,
  programId: string
): Program {
  const provider = new AnchorProvider(connection, wallet, {
    commitment: 'confirmed',
    preflightCommitment: 'confirmed',
  });
  return new Program(BACKER_ROUND_IDL, new PublicKey(programId), provider);
}

/**
 * Load the $SUMMON staking Anchor program.
 */
export function loadStakingProgram(
  connection: Connection,
  wallet: Wallet,
  programId: string
): Program {
  const provider = new AnchorProvider(connection, wallet, {
    commitment: 'confirmed',
    preflightCommitment: 'confirmed',
  });
  return new Program(STAKING_IDL, new PublicKey(programId), provider);
}

/**
 * Load the revenue-share Anchor program.
 */
export function loadRevenueShareProgram(
  connection: Connection,
  wallet: Wallet,
  programId: string
): Program {
  const provider = new AnchorProvider(connection, wallet, {
    commitment: 'confirmed',
    preflightCommitment: 'confirmed',
  });
  return new Program(REVENUE_SHARE_IDL, new PublicKey(programId), provider);
}

// =============================================================================
// Instruction Builders
// =============================================================================

/**
 * Build a backerRound initialize instruction.
 */
export async function buildInitializeBackerRoundIx(
  program: Program,
  roundAccount: PublicKey,
  authority: PublicKey,
  totalSlots: number,
  slotPriceUsd: number,
  platformFeeBps: number,
  deadline: Date
): Promise<ReturnType<typeof program.methods.initialize>> {
  return program.methods
    .initialize(
      totalSlots,
      new BN(slotPriceUsd * 100), // store as cents
      platformFeeBps,
      new BN(Math.floor(deadline.getTime() / 1000))
    )
    .accounts({
      backerRound: roundAccount,
      authority,
    });
}

/**
 * Build a purchaseSlot instruction.
 */
export async function buildPurchaseSlotIx(
  program: Program,
  roundAccount: PublicKey,
  backer: PublicKey
): Promise<ReturnType<typeof program.methods.purchaseSlot>> {
  return program.methods.purchaseSlot().accounts({
    backerRound: roundAccount,
    backer,
  });
}
